network: testnet4
default_port: 48333

# Our 7 nodes: 2 probes (0,1) + 5 groundtruth (2-6)
nodes:
  - id: 0
    role: probe
    rpcport: 48332
    rpcuser: expuser0
    rpcpassword: strongpassword0
    wallet: mywallet
    txprobe_log_file: /mnt/ssd/hdhphat-mindfullab/Bitcoin-TxProbe/txprobe_0.log
  - id: 1
    role: probe
    rpcport: 48335
    rpcuser: expuser1
    rpcpassword: strongpassword1
    txprobe_log_file: /mnt/ssd/hdhphat-mindfullab/Bitcoin-TxProbe/txprobe_1.log
  - id: 2
    role: groundtruth
    rpcport: 48338
    rpcuser: expuser2
    rpcpassword: strongpassword2
  - id: 3
    role: groundtruth
    rpcport: 48341
    rpcuser: expuser3
    rpcpassword: strongpassword3
  - id: 4
    role: groundtruth
    rpcport: 48344
    rpcuser: expuser4
    rpcpassword: strongpassword4
  - id: 5
    role: groundtruth
    rpcport: 48347
    rpcuser: expuser5
    rpcpassword: strongpassword5
  - id: 6
    role: groundtruth
    rpcport: 48350
    rpcuser: expuser5
    rpcpassword: strongpassword5

invblock:
  wait_time_sec: 5.0

tx_crafting:
  utxo_target_sats: 2000
  parent_fee_sats: 500
  marker_fee_sats: 500
  split_fee_rate_sat_vb: 2
  max_outputs_per_split_tx: 500
  max_source_size: 10
  poll_interval_sec: 10.0
  block_propagation_wait_sec: 15.0

txprobe_execution:
  invblock_wait_sec: 10.0
  flood_wait_sec: 1.0
  parent_wait_sec: 5.0
  marker_propagation_wait_sec: 10.0
  getdata_wait_sec: 15.0
  cleanup_wait_sec: 2.0

discovery:
  target_count: 25
  crawling_time_sec: 45
  poll_interval_sec: 5
  retry_interval_sec: 15
  clearnet_onetry_concurrency: 32
  tor_onetry_concurrency: 8
  max_addrman_age_days: 3

reachability:
  tor_proxy_host: "127.0.0.1"
  tor_proxy_port: 9050
  clearnet_timeout_sec: 5.0
  tor_timeout_sec: 30.0
  clearnet_concurrency: 50
  tor_concurrency: 20

dns_seeds:
  - seed.testnet4.bitcoin.sprovoost.nl
  - seed.testnet4.wiz.biz
